### PR TITLE
Allow configurability of all namespaces vs a specific namespace.

### PR DESCRIPTION
**Pull request by bigkevmcd**
This adds an option to allow configuration of all namespaces, or a specific namespace (configured by `RUNTIME_NAMESPACE`) for the manager cache.

Fix: #51

### CODE REVIEW

**Review by stefanprodan — APPROVED** [review]
LGTM

@bigkevmcd can you please signoff your commit. Thanks!

**Comment by squaremo** [comment]
> or a specific namespace (configured by `WATCH_NAMESPACE`) for the manager cache.

It doesn't look like it does this, but rather follows the GOTK convention of `--watchAllNamespaces=false` meaning use `RUNTIME_NAMESPACE` -- have I misunderstood?

**Comment by bigkevmcd** [comment]
> > or a specific namespace (configured by `WATCH_NAMESPACE`) for the manager cache.
> 
> It doesn't look like it does this, but rather follows the GOTK convention of `--watchAllNamespaces=false` meaning use `RUNTIME_NAMESPACE` -- have I misunderstood?

That's it, if you specify `--watchAllNamespaces=false` then it picks up the environment variable `WATCH_NAMESPACE`.

**Comment by stefanprodan** [comment]
The env var is called `RUNTIME_NAMESPACE`, the code is fine, just the PR description needs adjustments.

**Comment by bigkevmcd** [comment]
Doh, that's what I get for writing while in a meeting.

**Comment by bigkevmcd** [comment]
Some other components (built from the operator-sdk) use `WATCH_NAMESPACE` but that's more for controlling the namespace for watched resources, the change here (to configure the manager) changes the behaviour of the cache, but doesn't preclude watches in other namespaces (which might be RBACed elsewhere).

**Pull request merged**
